Syntax Editor Macro to populate macrosObj with records from the Syntax Editor Macro table
ServiceNowDevProgram/syntax_macros pull request #147
Opened 2024-10-10 21:28 UTC by snamjosh

2024-10-11 13:18 UTC, SapphicFire reviewed
This submission is not relevant to this repository. We encourage contributors to review the project's objectives and guidelines (see the README.md and CONTRIBUTING.md files) before submitting pull requests. 

This pull request has been copied from a community answer without proper attribution. Contributions should be original, and any referenced work should be properly attributed.

Source community answer with code copied and very minor alterations: [Service Portal: Syntax Editor Macros](https://www.servicenow.com/community/now-platform-articles/service-portal-syntax-editor-macros/ta-p/2311306). This is linked on the README.md file on the core repo

I am closing this and am opting to mark this as spam as I feel this was not done in good faith. As a fellow maintainer I am deeply disappointed.

2024-10-11 13:19 UTC, closed without merging

2024-10-11 14:28 UTC, snamjosh commented
@SapphicFire first of all, this is not a copied code since I am using it from years when Macros were introduced on the platform.how do you know that article you posted didn’t copied from me? I have been around this platform since 2013 and I have provided lot of solutions to hundreds of developers.

secondly, you need to brush your technical skills since I have this macro running  on my instance.

i am highly dissatisfied in your technical skills.

2024-10-11 14:29 UTC, snamjosh commented on Service Portal/spOnReady/readme.js
> +e.g This macro can be used during server script during service portal widget development.
I agree with this comment.

2024-10-14 15:23 UTC, Lacah requested changes

2024-10-14 15:23 UTC, Lacah commented on Service Portal/spOnReady/readme.js
> +e.g This macro can be used during server script during service portal widget development.
Can you plesase update the radme so this review can be closed and the PR merged? Thanks.

2024-10-14 16:11 UTC, snamjosh commented on Service Portal/spOnReady/readme.js
> +e.g This macro can be used during server script during service portal widget development.
@Lacah i updated readme to include review comments.