Added a script to group Incidents by Category using GlideAggregate
ServiceNowDevProgram/syntax_macros pull request #155
Opened 2024-10-17 03:43 UTC by Paulsylo25

Added a script to group Incidents by Category using GlideAggregate

2024-10-17 10:18 UTC, SapphicFire requested changes
Hi Paul!

This code is very similar to multiple that already exist in the GlideAggregate folder. Additionally, it is very specific and applies more like a code snippet. Could you please update it, perhaps using a method of GlideAggregate that does not feature in the other PRs?

At this stage I won't close but I cannot accept it as it would effectively be a duplicate

2024-10-17 19:38 UTC, Paulsylo25 commented
Hello Astrid,  I changed the code to group the incidents by the assigned user and count the number of incidents assigned to them and the average time takes to close. In this way, I demonstrate the usage of Glideaggregate

2024-10-17 19:39 UTC, Paulsylo25 reviewed
I reviewed the changes and I changed the code to group the incidents by the assigned user and count  the number of incidents assigned to them and average time take to close

2024-10-18 11:07 UTC, SapphicFire approved these changes

2024-10-18 11:07 UTC, merged